In [7]:
import numpy as np

In [8]:
m = np.asarray([[2,3,-4,12],[1,5,-1,12],[3,7,-3,20]])
print(m)

[[ 2  3 -4 12]
 [ 1  5 -1 12]
 [ 3  7 -3 20]]


In [9]:
def update_row(r2,r1):
    coeff = r2[0]/r1[0]
    r_temp = r2 - coeff*r1
    return(r_temp)

In [10]:
r1 = np.asarray([2,3,-4,12])
r2 = np.asarray([1,5,-1,12])
r2 = update_row(r2,r1)
print(r2)

[0.  3.5 1.  6. ]


In [11]:
def run_sub_mat(mat):
    m_temp = []
    m_temp.append(mat[0])
    for i in range(1,np.shape(mat)[0]):
        #print(i,i-1)
        m_temp.append(update_row(mat[i],mat[0]))
    return (np.asarray(m_temp) )
m_updated = run_itr(m)
print(m_updated)

NameError: name 'run_itr' is not defined

In [ ]:
sub_m = m_updated[1:,1:]
print(sub_m)
sub_m_updated = run_itr(sub_m)
print(sub_m_updated)

In [13]:
m = np.asarray([[1,2,3],[4,5,6],[7,8,9]])
print(m)
m[1:,1:] = np.asarray([[78,98],[76,45]])
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4 78 98]
 [ 7 76 45]]


In [14]:
m = np.asarray([[2,3,-4,12],[1,5,-1,12],[3,7,-3,20]])
print(m)
m = run_sub_mat(m)
print(m)
m[1:,1:] = run_sub_mat(m[1:,1:])
print(m)

[[ 2  3 -4 12]
 [ 1  5 -1 12]
 [ 3  7 -3 20]]
[[ 2.   3.  -4.  12. ]
 [ 0.   3.5  1.   6. ]
 [ 0.   2.5  3.   2. ]]
[[ 2.          3.         -4.         12.        ]
 [ 0.          3.5         1.          6.        ]
 [ 0.          0.          2.28571429 -2.28571429]]


In [15]:
def calc_ecl(mat):
    for i in 

SyntaxError: invalid syntax (<ipython-input-15-56c11957b926>, line 2)

In [ ]:
m = np.asarray([[2,3,-4,12],[1,5,-1,12],[3,7,-3,20]])
n = m[0:,0:]
print(m)
print(n)
m = run_sub_mat(m)
n = run_sub_mat(n)
print(m)
print(n)
m[0:,0:] = run_sub_mat(m[0:,0:])
print(m[0:,0:])
print(m)

In [ ]:
m = np.asarray([[2.0,3.0,-4.0,12.0],[1.0,5.0,-1.0,12.0],[3.0,7.0,-3.0,20.0]])
print(m)
m[0:,0:] = run_sub_mat(m[0:,0:])
print(m)
m[1:,1:] = run_sub_mat(m[1:,1:])
print(m)

In [ ]:
m = np.asarray([[2.0,3.0,-4.0,12.0],[1.0,5.0,-1.0,12.0],[3.0,7.0,-3.0,20.0]])
print(m)
m = run_sub_mat(m)
print(m)
m[1:,1:] = run_sub_mat(m[1:,1:])
print(m)

In [ ]:
def calc_ecl(m):
    temp_mat = np.copy(m)
    for i in range(len(temp_mat)):
        temp_mat[i:,i:] = run_sub_mat(temp_mat[i:,i:])
    return(temp_mat)
m = np.asarray([[2.0,3.0,-4.0,12.0],[1.0,5.0,-1.0,12.0],[3.0,7.0,-3.0,20.0]])
print(calc_ecl(m))

In [ ]:
m = np.asarray([[2.0,3.0,-4.0,12.0],[1.0,5.0,-1.0,12.0],[3.0,7.0,-3.0,20.0]])
m_ech = calc_ecl(m)

In [ ]:
m = [1,2,3,4]
print(m[:-1])

m3 = np.asarray([[2.0,3.0,-4.0,12.0],[1.0,5.0,-1.0,12.0],[3.0,7.0,-3.0,20.0]])

sol_vec = []

def calc_row_sol(mat_vec,sol_vec):
    const = mat_vec[-1]
    print(const)
    coeff_vec = mat_vec[1:-1]
    print(sol_vec)
    print(mat_vec)
    sol = (const - np.dot(coeff_vec,sol_vec))/mat_vec[0]
    return(sol)


In [ ]:
mat_vec = np.asarray([3.5,1.0,6.0])
sol_vec = np.asarray([1])
print(calc_row_sol(mat_vec,sol_vec))

In [23]:
l = []
l.insert(0,8)
print(l)

[8]


In [24]:
i = 2
ecl_m = 
mat_vec = m3[i:]
print(mat_vec)
#sol_vec = np.asarray([5])
#print(calc_row_sol(mat_vec,sol_vec))

SyntaxError: invalid syntax (<ipython-input-24-7756ec4ae4fc>, line 2)

In [ ]:
m = np.asarray([1,2,3,4])
print(m[:-2])

In [38]:
def calc_row(sol_vec,u_vec,const):
    print(u_vec[:-1],u_vec[-1])
    sol = (const-np.dot(sol_vec,u_vec[:-1]))/u_vec[-1]
    return sol

In [41]:
sol_vec = np.asarray([1.5,5/7])
u_vec = np.asarray([-4,1,16/7])
const = -3
print(calc_row(sol_vec,u_vec,const))

[-4.  1.] 2.2857142857142856
1.0


In [47]:
m = np.asarray([[2.0,3.0,-4.0],[1.0,5.0,-1.0],[3.0,7.0,-3.0]])
m = np.column_stack((m,[4,3,9]))
print(m)

[[ 2.  3. -4.  4.]
 [ 1.  5. -1.  3.]
 [ 3.  7. -3.  9.]]
